"""Pydantic JSON-schema provider port."""

from typing import Protocol

from pydantic import BaseModel, JsonValue


class SchemaProvider(Protocol):
    """Define JSON-schema generation from concrete Pydantic model classes."""

    def get_schema(self, model_type: type[BaseModel]) -> dict[str, JsonValue]:
        """Generate a JSON-safe schema for a Pydantic model class.

        Args:
            model_type: Concrete Pydantic output model.

        Returns:
            JSON schema generated by Pydantic v2.
        """
        ...
