"""Pydantic v2 JSON-schema provider implementation."""

from pydantic import BaseModel, JsonValue, TypeAdapter


class PydanticSchemaProvider:
    """Generate JSON-safe schemas directly from Pydantic output models."""

    def get_schema(self, model_type: type[BaseModel]) -> dict[str, JsonValue]:
        """Generate a JSON-safe schema using ``model_json_schema``.

        Args:
            model_type: Concrete Pydantic output model.

        Returns:
            Validated JSON schema generated by the supplied model class.
        """
        schema_adapter = TypeAdapter(dict[str, JsonValue])
        return schema_adapter.validate_python(model_type.model_json_schema())
